query getTutorials {
  tutorials {
    id
    title
    text
    createdBy {
      id
      name
    }
    createdAt
    codingLanguage
    latestVersion {
      version
      coderoadVersion
    }
  }
}
