query getTutorial($tutorialId: ID!) {
  tutorial(id: $tutorialId) {
    id
    testRunner
    codingLanguage
    repo {
      uri
      branch
    }
    version {
      version
      coderoadVersion
      data
    }
  }
}
